version: '3.7'
services:
  nginx:
    build:
      context: nginx
      target: developer
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build:
      context: app
      target: developer
    volumes:
      - ./app:/app
  front:
    build:
      context: front
      target: developer
    volumes:
      - ./front:/app
    depends_on:
      - app
    ports:
      - 8081:8080
