version: '3.7'
services:
  nginx:
    build:
      context: nginx
      target: developer
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build:
      context: app
      target: developer
    volumes:
      - ./app:/app
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
#    depends_on:
#      - db
  front:
    build:
      context: front
      target: developer
    volumes:
      - ./front:/app
    depends_on:
      - app
    ports:
      - 8081:8080
#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - 5432:5432
